### ISSUE TITLE
About training time and dataloader of ImageNet-10 and ImageNet-dogs

### ISSUE THREAD

**Issue by kasteric** [Yunfan-Li/Twin-Contrastive-Learning#14]
Hi, thanks for your awesome work! I am wondering how much time do u take to train ImageNet-10 for 1000 epochs.
When I was training ImageNet-10 using ImageFolder, the training speed, especially the I/O speed of dataloader was very slow,  do you have the same issues？

**Comment by Yunfan-Li** [comment]
Hi, it takes about 14 hours to train ImageNet-10 on a 3090 GPU. You could try different num_worker value of dataloader.

**Comment by kasteric** [comment]
Thanks for your kind response!
