### ISSUE TITLE
pretrained models and code for text experiments plz

### ISSUE THREAD

**Issue by MohammadVahidiPro** [Yunfan-Li/Twin-Contrastive-Learning#23]
Hi, I hope you're doing well. I've been following your impressive research on contrastive learning and find it inspiring.

I am particularly interested in your experiments with text datasets, You've shared the code and pretrained checkpoints for experiments with image datasets, so I was wondering if you have any plans to do the same for text experiments. If you have any resources, code, or pretrained models to share, I would be incredibly grateful for the opportunity to explore and learn from them. I understand others have asked this before, so I'm just wondering if there's any update on this

Thank you for your valuable contributions to the community, and I sincerely appreciate your consideration.

**Comment by Yunfan-Li** [comment]
Thanks for your interest. The code for text clustering is implemented by another co-author and released on https://github.com/XLearning-SCU/2022-IJCV-TCL/tree/main/TextClustering.

**Comment by MohammadVahidiPro** [comment]
Thank you for your prompt response.
As a beginner in this field, I truly appreciate your help. I'm eager to replicate your impressive results on text datasets using my single-GPU laptop (4gb gpu/16gb ram). I'm not sure if I should ask you this but before proceeding, I would like to know if running your experiments on my hardware is feasible within a reasonable timeframe. Could you provide a rough estimate of the expected time for completion? (is it like hours? days? or...) If it's too time-consuming, I'd consider getting more compute.

Again, I want to express my gratitude for your valuable help. Your research is of great interest to me, and I'm looking forward to your future papers.

**Comment by Yunfan-Li** [comment]
For your reference, we trained our model on the biomedical dataset for ~2 days with a single Nvidia RTX 3090 GPU (24G).

**Comment by MohammadVahidiPro** [comment]
thanks
