### ISSUE TITLE
Pretrained models 

### ISSUE THREAD

**Issue by aabbas90** [Yunfan-Li/Twin-Contrastive-Learning#4]
Hi,

1. Could you please make the pretrained models available? 
2. I am interested in reproducing TCL_{ICH} results from Table 3. I guess k-means clustering is performed on the tensor `z` from https://github.com/Yunfan-Li/Twin-Contrastive-Learning/blob/1f663c00b724d8a76423533f047aab33a9103fcf/model.py#L208. Is that correct? 

Many thanks!

**Comment by Yunfan-Li** [comment]
1. The pretrained model to larger than the file size limit of 25MB. I don't know how to upload it.
2. Yes. That is correct.

**Comment by aabbas90** [comment]
Thanks for prompt reply! You can possibly try uploading on [onedrive](https://onedrive.live.com/)

**Comment by Yunfan-Li** [comment]
I have uploaded the pretrained model on CIFAR-10 and ImageNet on Google Drive (https://drive.google.com/drive/folders/1fQswZsF4cr00ox7XHDrnbZ66kLkG8I0P?usp=sharing).
