### ISSUE TITLE
Boosting does not seem to be improving performance

### ISSUE THREAD

**Issue by RuyangWang** [Yunfan-Li/Twin-Contrastive-Learning#9]
I ran 1000 epochs of training and 200 epochs of boosting, but NMI/ACC/ARI is not improved during the boosting. Are there any parameters that need to be changed in boost.py? 
FYI: My dataset is smaller than yours, with 10 classes and each class contains 300 samples.

**Comment by Yunfan-Li** [comment]
You could observe the accuracy and number of selected pseudo labels. And you may need to make the pseudo label selection stricter if the quality of pseudo labels is not good enough.

**Comment by RuyangWang** [comment]
Thanks for the quick reply! In which class/variable can I make pseudo label selection stricter?

**Comment by Yunfan-Li** [comment]
You could increase the alpha value and decrease the gamma value in pseudo labeling in the InstanceLossBoost class.

**Comment by RuyangWang** [comment]
Thanks, I will try it out!
